# Generated by Django 5.2.1 on 2025-05-15 15:11

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_warehouselocation_batch_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='GPSDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=100, unique=True, verbose_name='ID пристрою')),
                ('model', models.CharField(max_length=100, verbose_name='Модель пристрою')),
                ('serial_number', models.CharField(max_length=100, unique=True, verbose_name='Серійний номер')),
                ('installation_date', models.DateField(verbose_name='Дата встановлення')),
                ('status', models.CharField(choices=[('active', 'Активний'), ('inactive', 'Неактивний'), ('malfunction', 'Несправний')], default='active', max_length=20, verbose_name='Статус')),
                ('last_connection', models.DateTimeField(blank=True, null=True, verbose_name="Останнє з'єднання")),
                ('notes', models.TextField(blank=True, verbose_name='Примітки')),
            ],
            options={
                'verbose_name': 'GPS-пристрій',
                'verbose_name_plural': 'GPS-пристрої',
            },
        ),
        migrations.AddField(
            model_name='route',
            name='actual_end_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Фактичний час закінчення'),
        ),
        migrations.AddField(
            model_name='route',
            name='actual_start_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Фактичний час початку'),
        ),
        migrations.AddField(
            model_name='route',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='route',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Примітки'),
        ),
        migrations.AddField(
            model_name='route',
            name='planned_distance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Запланована відстань (км)'),
        ),
        migrations.AddField(
            model_name='route',
            name='planned_end_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Запланований час закінчення'),
        ),
        migrations.AddField(
            model_name='route',
            name='planned_start_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Запланований час початку'),
        ),
        migrations.AddField(
            model_name='route',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='routepoint',
            name='actual_arrival_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Фактичний час прибуття'),
        ),
        migrations.AddField(
            model_name='routepoint',
            name='completed',
            field=models.BooleanField(default=False, verbose_name='Виконано'),
        ),
        migrations.AddField(
            model_name='routepoint',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Широта'),
        ),
        migrations.AddField(
            model_name='routepoint',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Довгота'),
        ),
        migrations.AddField(
            model_name='routepoint',
            name='planned_arrival_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Запланований час прибуття'),
        ),
        migrations.AlterField(
            model_name='route',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_routes', to=settings.AUTH_USER_MODEL, verbose_name='Водій'),
        ),
        migrations.CreateModel(
            name='GPSLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Широта')),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Довгота')),
                ('altitude', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Висота (м)')),
                ('speed', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Швидкість (км/год)')),
                ('direction', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Напрямок (градуси)')),
                ('timestamp', models.DateTimeField(verbose_name='Час фіксації')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='inventory.gpsdevice', verbose_name='GPS-пристрій')),
                ('route', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gps_path', to='inventory.route', verbose_name="Пов'язаний маршрут")),
            ],
            options={
                'verbose_name': 'GPS-локація',
                'verbose_name_plural': 'GPS-локації',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Назва інвентаризації')),
                ('start_date', models.DateTimeField(verbose_name='Дата початку')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата завершення')),
                ('status', models.CharField(choices=[('planned', 'Заплановано'), ('in_progress', 'В процесі'), ('completed', 'Завершено'), ('canceled', 'Скасовано')], default='planned', max_length=20)),
                ('notes', models.TextField(blank=True, verbose_name='Примітки')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ManyToManyField(blank=True, related_name='assigned_inventories', to=settings.AUTH_USER_MODEL, verbose_name='Призначені користувачі')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_inventories', to=settings.AUTH_USER_MODEL)),
                ('locations', models.ManyToManyField(blank=True, related_name='inventories', to='inventory.warehouselocation', verbose_name='Складські локації')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventories', to='inventory.warehouse')),
            ],
            options={
                'verbose_name': 'Інвентаризація',
                'verbose_name_plural': 'Інвентаризації',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='transaction',
            name='inventory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='inventory.inventory'),
        ),
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expected_quantity', models.PositiveIntegerField(verbose_name='Очікувана кількість')),
                ('actual_quantity', models.PositiveIntegerField(blank=True, null=True, verbose_name='Фактична кількість')),
                ('counted_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, verbose_name='Примітки')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_items', to='inventory.batch')),
                ('counted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='counted_items', to=settings.AUTH_USER_MODEL)),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.inventory')),
            ],
            options={
                'verbose_name': 'Елемент інвентаризації',
                'verbose_name_plural': 'Елементи інвентаризації',
                'unique_together': {('inventory', 'batch')},
            },
        ),
        migrations.CreateModel(
            name='InventoryDiscrepancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('difference', models.IntegerField(verbose_name="Різниця (може бути від'ємною)")),
                ('status', models.CharField(choices=[('pending', 'Очікує розгляду'), ('investigated', 'Розслідувано'), ('resolved', 'Вирішено'), ('ignored', 'Ігноровано')], default='pending', max_length=20)),
                ('reason', models.CharField(choices=[('theft', 'Крадіжка'), ('damage', 'Пошкодження'), ('error', 'Помилка обліку'), ('expiration', 'Термін придатності минув'), ('miscounted', 'Помилка підрахунку'), ('unknown', 'Невідомо'), ('other', 'Інше')], default='unknown', max_length=20, verbose_name='Причина розбіжності')),
                ('resolution_note', models.TextField(blank=True, verbose_name='Примітка щодо вирішення')),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discrepancies', to='inventory.inventory')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_discrepancies', to=settings.AUTH_USER_MODEL)),
                ('inventory_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discrepancies', to='inventory.inventoryitem')),
            ],
            options={
                'verbose_name': 'Розбіжність інвентаризації',
                'verbose_name_plural': 'Розбіжності інвентаризації',
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Назва')),
                ('plate_number', models.CharField(max_length=20, unique=True, verbose_name='Номерний знак')),
                ('type', models.CharField(choices=[('truck', 'Вантажівка'), ('van', 'Фургон'), ('car', 'Легковий автомобіль'), ('special', 'Спеціальний транспорт')], max_length=20, verbose_name='Тип транспорту')),
                ('model', models.CharField(max_length=100, verbose_name='Модель')),
                ('year', models.PositiveIntegerField(verbose_name='Рік випуску')),
                ('capacity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Вантажопідйомність (кг)')),
                ('volume', models.DecimalField(decimal_places=2, max_digits=10, verbose_name="Об'єм вантажного відсіку (м³)")),
                ('status', models.CharField(choices=[('active', 'Активний'), ('inactive', 'Неактивний'), ('maintenance', 'На обслуговуванні'), ('repair', 'На ремонті')], default='active', max_length=20, verbose_name='Статус')),
                ('last_maintenance', models.DateField(blank=True, null=True, verbose_name='Дата останнього ТО')),
                ('next_maintenance', models.DateField(blank=True, null=True, verbose_name='Дата наступного ТО')),
                ('notes', models.TextField(blank=True, verbose_name='Примітки')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_vehicles', to=settings.AUTH_USER_MODEL, verbose_name='Водій')),
                ('warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicles', to='inventory.warehouse', verbose_name='Прикріплений до складу')),
            ],
            options={
                'verbose_name': 'Транспортний засіб',
                'verbose_name_plural': 'Транспортні засоби',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RouteGPSLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(blank=True, null=True, verbose_name='Час початку')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='Час закінчення')),
                ('distance', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Пройдена відстань (км)')),
                ('avg_speed', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Середня швидкість (км/год)')),
                ('max_speed', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Максимальна швидкість (км/год)')),
                ('fuel_used', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Використано палива (л)')),
                ('notes', models.TextField(blank=True, verbose_name='Примітки')),
                ('end_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='route_ends', to='inventory.gpslocation', verbose_name='Кінцева точка')),
                ('route', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gps_log', to='inventory.route', verbose_name='Маршрут')),
                ('start_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='route_starts', to='inventory.gpslocation', verbose_name='Початкова точка')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_logs', to='inventory.vehicle', verbose_name='Транспортний засіб')),
            ],
            options={
                'verbose_name': 'GPS-лог маршруту',
                'verbose_name_plural': 'GPS-логи маршрутів',
            },
        ),
        migrations.AddField(
            model_name='gpslocation',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gps_locations', to='inventory.vehicle', verbose_name='Транспортний засіб'),
        ),
        migrations.AddField(
            model_name='gpsdevice',
            name='vehicle',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gps_device', to='inventory.vehicle', verbose_name='Транспортний засіб'),
        ),
        migrations.AlterField(
            model_name='route',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_routes', to='inventory.vehicle', verbose_name='Транспортний засіб'),
        ),
        migrations.AddIndex(
            model_name='gpslocation',
            index=models.Index(fields=['vehicle', 'timestamp'], name='inventory_g_vehicle_6ccdbe_idx'),
        ),
        migrations.AddIndex(
            model_name='gpslocation',
            index=models.Index(fields=['route', 'timestamp'], name='inventory_g_route_i_e83703_idx'),
        ),
    ]
